// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Theme_Colors = require("../theme/Theme_Colors.bs.js");

var defaultTheme_textColor = Theme_Colors.light.foreground;

var defaultTheme = {
  borderRadius: 4,
  borderWidth: 2,
  textColor: defaultTheme_textColor,
  height: 35,
  paddingHorizontal: 14,
  textTransform: /* none */-922086728
};

exports.defaultTheme = defaultTheme;
/* No side effect */
