// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Box = require("../box/Box.bs.js");
var Theme = require("../theme/Theme.bs.js");
var React = require("react");
var Caml_option = require("bs-platform/lib/js/caml_option.js");
var ReactNative = require("react-native");

function Input(Props) {
  var componentOpt = Props.component;
  var style = Props.style;
  var component = componentOpt !== undefined ? Caml_option.valFromOption(componentOpt) : React.createElement(ReactNative.TextInput, {
          onFocus: (function (param) {
              
            })
        });
  var theme = Theme.useTheme(undefined);
  var resolvedStyle = [style];
  var inputElement = React.createElement(Box.make, {
        ph: theme.input.paddingHorizontal,
        h: theme.input.height,
        borderWidth: 1,
        borderRadius: theme.input.borderRadius,
        borderColor: theme.colors.info,
        component: component
      });
  return React.cloneElement(inputElement, {
              style: resolvedStyle,
              onFocus: ""
            });
}

var make = Input;

var $$default = Input;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Box Not a pure module */
