// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Box = require("../box/Box.bs.js");
var React = require("react");

function Spacer(Props) {
  var xOpt = Props.x;
  var yOpt = Props.y;
  var x = xOpt !== undefined ? xOpt : 16;
  var y = yOpt !== undefined ? yOpt : 16;
  return React.createElement(Box.make, {
              w: x,
              h: y
            });
}

var make = Spacer;

var $$default = Spacer;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Box Not a pure module */
