// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactNative = require("react-native");

function Spacer(Props) {
  var xOpt = Props.x;
  var yOpt = Props.y;
  var x = xOpt !== undefined ? xOpt : 16;
  var y = yOpt !== undefined ? yOpt : 16;
  var style = {
    height: y,
    width: x
  };
  return React.createElement(ReactNative.View, {
              style: style
            });
}

var make = Spacer;

var $$default = Spacer;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
