// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Theme_Colors = require("../theme/Theme_Colors.bs.js");

var defaultTheme_textColor = {
  solid: Theme_Colors.light.background,
  outline: Theme_Colors.light.foreground,
  ghost: Theme_Colors.light.foreground
};

var defaultTheme_paddingVertical = {
  small: 6,
  normal: 8,
  big: 16
};

var defaultTheme_paddingHorizontal = {
  small: 6,
  normal: 16,
  big: 32
};

var defaultTheme = {
  borderRadius: 4,
  textColor: defaultTheme_textColor,
  paddingVertical: defaultTheme_paddingVertical,
  paddingHorizontal: defaultTheme_paddingHorizontal
};

exports.defaultTheme = defaultTheme;
/* No side effect */
