// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var $great$great$eq = Belt_Option.flatMap;

var $less$$great = Belt_Option.map;

exports.$great$great$eq = $great$great$eq;
exports.$less$$great = $less$$great;
/* No side effect */
