// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactNative = require("react-native");

function LoadingSpinner(Props) {
  return React.createElement(ReactNative.ActivityIndicator, { });
}

var make = LoadingSpinner;

exports.make = make;
/* react Not a pure module */
