// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReactNative = require("react-native");

var isWeb = ReactNative.Platform.OS === "web";

function Hoverable(Props) {
  var children = Props.children;
  var onHoverIn = Props.onHoverIn;
  var onHoverOut = Props.onHoverOut;
  if (!isWeb) {
    return children;
  }
  var onMouseEnter = function (param) {
    return Curry._1(onHoverIn, undefined);
  };
  var onMouseLeave = function (param) {
    return Curry._1(onHoverOut, undefined);
  };
  return React.createElement("span", {
              onMouseEnter: onMouseEnter,
              onMouseLeave: onMouseLeave
            }, children);
}

var make = Hoverable;

var $$default = Hoverable;

exports.isWeb = isWeb;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* isWeb Not a pure module */
