// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactNative = require("react-native");

var styles = ReactNative.StyleSheet.create({
      text: { }
    });

function $$Text(Props) {
  var value = Props.value;
  return React.createElement(ReactNative.Text, {
              children: value
            });
}

var make = $$Text;

var $$default = $$Text;

exports.styles = styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* styles Not a pure module */
