// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var defaultTheme = {
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 20,
    _2xl: 24,
    _3xl: 30,
    _4xl: 36,
    _6xl: 64,
    _5xl: 48
  }
};

exports.defaultTheme = defaultTheme;
/* No side effect */
