// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Theme = require("../theme/Theme.bs.js");
var React = require("react");
var ReactNative = require("react-native");

function $$Text(Props) {
  var value = Props.value;
  var styleText = Props.styleText;
  var sizeOpt = Props.size;
  var size = sizeOpt !== undefined ? sizeOpt : /* md */24407;
  var theme = Theme.useTheme(undefined);
  var fontSize = size >= 1056022183 ? (
      size !== 1056071912 ? (
          size >= 1056171370 ? (
              size >= 1056221099 ? theme.text.fontSize._6xl : theme.text.fontSize._5xl
            ) : (
              size >= 1056121641 ? theme.text.fontSize._4xl : theme.text.fontSize._2xl
            )
        ) : theme.text.fontSize._3xl
    ) : (
      size !== 24407 ? (
          size >= 26868 ? (
              size >= 26875 ? theme.text.fontSize.xs : theme.text.fontSize.xl
            ) : (
              size >= 25754 ? theme.text.fontSize.sm : theme.text.fontSize.lg
            )
        ) : theme.text.fontSize.md
    );
  var resolvedStyle = [
    {
      fontFamily: theme.text.fontFamily,
      fontSize: fontSize
    },
    styleText
  ];
  return React.createElement(ReactNative.Text, {
              style: resolvedStyle,
              children: value
            });
}

var make = $$Text;

var $$default = $$Text;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Theme Not a pure module */
