// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var defaultTheme = {
  fontSize: {
    xs: 8.96,
    sm: 11.2,
    md: 14,
    lg: 17.5,
    xl: 21.88,
    _2xl: 27.34,
    _3xl: 34.18,
    _4xl: 42.72,
    _5xl: 53.41,
    _6xl: 66.76
  },
  fontFamily: ""
};

exports.defaultTheme = defaultTheme;
/* No side effect */
