// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var light = {
  background: "#fff",
  foreground: "#000",
  neutral100: "#fafafa",
  neutral200: "#eaeaea",
  neutral300: "#999",
  neutral400: "#888",
  neutral500: "#666",
  neutral600: "#444",
  neutral700: "#333",
  neutral800: "#111",
  neutral900: "#060606",
  primary: "#3f51b5",
  primaryLight: "#757de8",
  primaryDark: "#002984",
  secondary: "#e91e63",
  secondaryLight: "#ff6090",
  secondaryDark: "#b0003a",
  success: "#4caf50",
  successLight: "#80e27e",
  successDark: "#087f23",
  danger: "#f44336",
  dangerLight: "#ff7961",
  dangerDark: "#ba000d",
  info: "#2196f3",
  infoLight: "#6ec6ff",
  infoDark: "#0069c0",
  warning: "#ffc107",
  warningLight: "#fff350",
  warningDark: "#c79100"
};

exports.light = light;
/* No side effect */
