// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var defaultTheme = {
  xs: 0,
  sm: 576,
  md: 768,
  lg: 992,
  xl: 1200
};

exports.defaultTheme = defaultTheme;
/* No side effect */
