// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


function dp(prim) {
  return prim;
}

var defaultTheme = [
  0,
  4,
  8,
  16,
  32,
  64,
  128,
  256,
  512
];

exports.dp = dp;
exports.defaultTheme = defaultTheme;
/* No side effect */
