// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var light = {
  background: "#fff",
  foreground: "#000",
  neutral100: "#fafafa",
  neutral200: "#eaeaea",
  neutral300: "#999",
  neutral400: "#888",
  neutral500: "#888",
  neutral600: "#888",
  neutral700: "#888",
  neutral800: "#888",
  neutral900: "#111",
  primary: "#333",
  primaryLight: "#444",
  primaryDark: "#222",
  secondary: "#333",
  secondaryLight: "#444",
  secondaryDark: "#222",
  success: "#333",
  successLight: "#444",
  successDark: "#222",
  error: "#333",
  errorLight: "#444",
  errorDark: "#222",
  info: "#333",
  infoLight: "#444",
  infoDark: "#222",
  warning: "#333",
  warningLight: "#444",
  warningDark: "#222"
};

exports.light = light;
/* No side effect */
