// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';


var light = {
  background: "#fff",
  foreground: "#000",
  neutral100: "#fafafa",
  neutral200: "#eaeaea",
  neutral300: "#999",
  neutral400: "#888",
  neutral500: "#666",
  neutral600: "#444",
  neutral700: "#333",
  neutral800: "#111",
  neutral900: "#060606",
  primary: "#3f51b5",
  primaryLight: "#7986cb",
  primaryLighter: "#c5cae9",
  primaryDark: "#303f9f",
  primaryDarker: "#1a237e",
  secondary: "#e91e63",
  secondaryLight: "#f06292",
  secondaryLighter: "#f8bbd0",
  secondaryDark: "#c2185b",
  secondaryDarker: "#880e4f",
  success: "#4caf50",
  successLight: "#81c784",
  successLighter: "#c8e6c9",
  successDark: "#388e3c",
  successDarker: "#1b5e20",
  danger: "#f44336",
  dangerLight: "#e57373",
  dangerLighter: "#ffcdd2",
  dangerDark: "#ba000d",
  dangerDarker: "#b71c1c",
  info: "#2196f3",
  infoLight: "#64b5f6",
  infoLighter: "#bbdefb",
  infoDark: "#1976d2",
  infoDarker: "#0d47a1",
  warning: "#ffc107",
  warningLight: "#ffd54f",
  warningLighter: "#ffecb3",
  warningDark: "#ffa000",
  warningDarker: "#ff6f00"
};

exports.light = light;
/* No side effect */
