// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Button_Theme = require("../button/Button_Theme.bs.js");
var Theme_Colors = require("./Theme_Colors.bs.js");

var defaultTheme = {
  colors: Theme_Colors.light,
  button: Button_Theme.defaultTheme
};

var themeContext = React.createContext(defaultTheme);

function makeProps(value, children, param) {
  return {
          value: value,
          children: children
        };
}

var make = themeContext.Provider;

var Colors;

var $$default = make;

exports.Colors = Colors;
exports.defaultTheme = defaultTheme;
exports.themeContext = themeContext;
exports.makeProps = makeProps;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* themeContext Not a pure module */
